main: main.c AccountSystem.c ../CommonImplement/NetworkInterface/NetworkInterface.c
	gcc -o main main.c AccountSystem.c ../CommonImplement/NetworkInterface/NetworkInterface.c
clean:
	rm -rf *o main
