main: main.c AccountSystem.c AccountSystem.h  TerminalInterface.c TerminalInterface.h DailyAccountInformation.h
	gcc -o main main.c AccountSystem.c AccountSystem.h  TerminalInterface.c TerminalInterface.h DailyAccountInformation.h
clean:
	rm -rf *o main
