main: main.c BusControl.c ../CommonImplement/NetworkInterface/NetworkInterface.c ../CommonImplement/FileIoInterface/FileIoInterface.c ../CommonImplement/Timer/InnerTimer.c
	gcc -o main main.c BusControl.c ../CommonImplement/NetworkInterface/NetworkInterface.c ../CommonImplement/FileIoInterface/FileIoInterface.c ../CommonImplement/Timer/InnerTimer.c
clean:
	rm -rf *o main
