main: main.c BusControl.c ../CommonImplement/NetworkInterface/NetworkInterface.c ../CommonImplement/FileIoInterface/FileIoInterface.c
	gcc -o main main.c BusControl.c ../CommonImplement/NetworkInterface/NetworkInterface.c ../CommonImplement/FileIoInterface/FileIoInterface.c
clean:
	rm -rf *o main
